import { ConnectServices } from "./ConnectServices.js";
import { Authorization } from "../../gen/avn/connect/v1/authorization_pb.js";
export declare const Hostname = "avnfs.com";
export declare const UrlPrefix = "https://avnfs.com";
export declare const DuplicateUploadEventType = "duplicate";
export declare const TypeQueryParam = "type";
export declare const SizeQueryParam = "size";
export declare const NameQueryParam = "name";
export type FileSpec = {
    hash: string;
    sizeBytes: number;
    mediaType: string;
    fileName?: string;
};
export declare function isValidUrl(url: URL): boolean;
export declare function decodeUrl(url: URL): FileSpec;
export declare function encodeUrl(spec: FileSpec): URL;
export declare function updateFilename(url: URL, name: string | undefined): URL;
export declare function uploadArrayBuffer(buffer: ArrayBuffer, ConnectServices: ConnectServices, auth: Authorization, mediaType: string, fileName?: string | undefined, progressCallback?: ((event: ProgressEvent) => any) | undefined, signal?: AbortSignal | undefined): Promise<URL>;
export declare function uploadFilePath(path: string, Connect: ConnectServices, auth: Authorization, mediaType: string, fileName?: string | undefined, progressCallback?: ((event: ProgressEvent) => any) | undefined, signal?: AbortSignal | undefined): Promise<URL>;
export declare function uploadFile(file: File, ConnectServices: ConnectServices, auth: Authorization, mediaTypeOverride?: string | undefined, fileNameOverride?: string | undefined, progressCallback?: ((event: ProgressEvent) => any) | undefined, signal?: AbortSignal | undefined): Promise<URL>;
