import { PromiseClient } from "@connectrpc/connect";
import { ActivityService } from "../../gen/avn/connect/v1/activities_connect.js";
import { AvnfsService } from "../../gen/avn/connect/v1/avnfs_connect.js";
import { BlockadeService } from "../../gen/avn/connect/v1/blockade_connect.js";
import { CategoryService } from "../../gen/avn/connect/v1/categories_connect.js";
import { CertificateService } from "../../gen/avn/connect/v1/certificates_connect.js";
import { ChannelService } from "../../gen/avn/connect/v1/channels_connect.js";
import { ClientService } from "../../gen/avn/connect/v1/clients_connect.js";
import { CloudService } from "../../gen/avn/connect/v1/cloud_connect.js";
import { ContentService } from "../../gen/avn/connect/v1/content_connect.js";
import { CountryService } from "../../gen/avn/connect/v1/countries_connect.js";
import { DimensionService } from "../../gen/avn/connect/v1/dimensions_connect.js";
import { GeoService } from "../../gen/avn/connect/v1/geo_connect.js";
import { Health } from "../../gen/grpc/health/v1/healthcheck_connect.js";
import { KtxService } from "../../gen/avn/connect/v1/ktx_connect.js";
import { LanguageService } from "../../gen/avn/connect/v1/languages_connect.js";
import { LicenseService } from "../../gen/avn/connect/v1/licenses_connect.js";
import { MediaService } from "../../gen/avn/connect/v1/media_connect.js";
import { NeighborService } from "../../gen/avn/connect/v1/neighbors_connect.js";
import { OrganizationService } from "../../gen/avn/connect/v1/organizations_connect.js";
import { PassService } from "../../gen/avn/connect/v1/passes_connect.js";
import { PermissionService } from "../../gen/avn/connect/v1/permissions_connect.js";
import { ProfileService } from "../../gen/avn/connect/v1/profiles_connect.js";
import { RoleService } from "../../gen/avn/connect/v1/roles_connect.js";
import { RoomService } from "../../gen/avn/connect/v1/rooms_connect.js";
import { TagService } from "../../gen/avn/connect/v1/tags_connect.js";
import { ThreeSixtyCitiesService } from "../../gen/avn/connect/v1/three_sixty_cities_connect.js";
import { TranslationService } from "../../gen/avn/connect/v1/translations_connect.js";
import { UserService } from "../../gen/avn/connect/v1/users_connect.js";
export declare const GwebUrl = "https://gweb.avncloud.com";
export declare const GwebAlphaUrl = "https://gweb-alpha.avncloud.com";
export declare class ConnectServices {
    readonly gwebUrl: string;
    constructor(gwebUrl?: string);
    private transport;
    Activities: PromiseClient<typeof ActivityService>;
    Avnfs: PromiseClient<typeof AvnfsService>;
    Blockade: PromiseClient<typeof BlockadeService>;
    Categories: PromiseClient<typeof CategoryService>;
    Certificates: PromiseClient<typeof CertificateService>;
    Channels: PromiseClient<typeof ChannelService>;
    Clients: PromiseClient<typeof ClientService>;
    Cloud: PromiseClient<typeof CloudService>;
    Content: PromiseClient<typeof ContentService>;
    Countries: PromiseClient<typeof CountryService>;
    Dimensions: PromiseClient<typeof DimensionService>;
    Geo: PromiseClient<typeof GeoService>;
    Health: PromiseClient<typeof Health>;
    Ktx: PromiseClient<typeof KtxService>;
    Languages: PromiseClient<typeof LanguageService>;
    Licenses: PromiseClient<typeof LicenseService>;
    Media: PromiseClient<typeof MediaService>;
    Neighbors: PromiseClient<typeof NeighborService>;
    Organizations: PromiseClient<typeof OrganizationService>;
    Passes: PromiseClient<typeof PassService>;
    Permissions: PromiseClient<typeof PermissionService>;
    Profiles: PromiseClient<typeof ProfileService>;
    Roles: PromiseClient<typeof RoleService>;
    Rooms: PromiseClient<typeof RoomService>;
    Tags: PromiseClient<typeof TagService>;
    ThreeSixtyCities: PromiseClient<typeof ThreeSixtyCitiesService>;
    Translations: PromiseClient<typeof TranslationService>;
    Users: PromiseClient<typeof UserService>;
}
