import { Client } from "@connectrpc/connect";
import { ActivityService } from "../../gen/avn/connect/v1/activities_connect.js";
import { AvnfsService } from "../../gen/avn/connect/v1/avnfs_connect.js";
import { BlockadeService } from "../../gen/avn/connect/v1/blockade_connect.js";
import { CategoryService } from "../../gen/avn/connect/v1/categories_connect.js";
import { CertificateService } from "../../gen/avn/connect/v1/certificates_connect.js";
import { ChannelService } from "../../gen/avn/connect/v1/channels_connect.js";
import { ClientService } from "../../gen/avn/connect/v1/clients_connect.js";
import { CloudService } from "../../gen/avn/connect/v1/cloud_connect.js";
import { ContentService } from "../../gen/avn/connect/v1/content_connect.js";
import { CountryService } from "../../gen/avn/connect/v1/countries_connect.js";
import { DimensionService } from "../../gen/avn/connect/v1/dimensions_connect.js";
import { GeoService } from "../../gen/avn/connect/v1/geo_connect.js";
import { Health } from "../../gen/grpc/health/v1/healthcheck_connect.js";
import { KtxService } from "../../gen/avn/connect/v1/ktx_connect.js";
import { LanguageService } from "../../gen/avn/connect/v1/languages_connect.js";
import { LicenseService } from "../../gen/avn/connect/v1/licenses_connect.js";
import { MediaService } from "../../gen/avn/connect/v1/media_connect.js";
import { NeighborService } from "../../gen/avn/connect/v1/neighbors_connect.js";
import { OrganizationService } from "../../gen/avn/connect/v1/organizations_connect.js";
import { PassService } from "../../gen/avn/connect/v1/passes_connect.js";
import { PermissionService } from "../../gen/avn/connect/v1/permissions_connect.js";
import { ProfileService } from "../../gen/avn/connect/v1/profiles_connect.js";
import { RoleService } from "../../gen/avn/connect/v1/roles_connect.js";
import { RoomService } from "../../gen/avn/connect/v1/rooms_connect.js";
import { SpeechService } from "../../gen/avn/connect/v1/speech_connect.js";
import { TagService } from "../../gen/avn/connect/v1/tags_connect.js";
import { ThreeSixtyCitiesService } from "../../gen/avn/connect/v1/three_sixty_cities_connect.js";
import { TranscriptionService } from "../../gen/avn/connect/v1/transcriptions_connect.js";
import { TranslationService } from "../../gen/avn/connect/v1/translations_connect.js";
import { UserService } from "../../gen/avn/connect/v1/users_connect.js";
export declare const GwebUrl = "https://gweb.avncloud.com";
export declare const GwebAlphaUrl = "https://gweb-alpha.avncloud.com";
export declare class ConnectServices {
    readonly gwebUrl: string;
    constructor(gwebUrl?: string);
    private transport;
    Activities: Client<typeof ActivityService>;
    Avnfs: Client<typeof AvnfsService>;
    Blockade: Client<typeof BlockadeService>;
    Categories: Client<typeof CategoryService>;
    Certificates: Client<typeof CertificateService>;
    Channels: Client<typeof ChannelService>;
    Clients: Client<typeof ClientService>;
    Cloud: Client<typeof CloudService>;
    Content: Client<typeof ContentService>;
    Countries: Client<typeof CountryService>;
    Dimensions: Client<typeof DimensionService>;
    Geo: Client<typeof GeoService>;
    Health: Client<typeof Health>;
    Ktx: Client<typeof KtxService>;
    Languages: Client<typeof LanguageService>;
    Licenses: Client<typeof LicenseService>;
    Media: Client<typeof MediaService>;
    Neighbors: Client<typeof NeighborService>;
    Organizations: Client<typeof OrganizationService>;
    Passes: Client<typeof PassService>;
    Permissions: Client<typeof PermissionService>;
    Profiles: Client<typeof ProfileService>;
    Roles: Client<typeof RoleService>;
    Rooms: Client<typeof RoomService>;
    Speech: Client<typeof SpeechService>;
    Tags: Client<typeof TagService>;
    ThreeSixtyCities: Client<typeof ThreeSixtyCitiesService>;
    Transcriptions: Client<typeof TranscriptionService>;
    Translations: Client<typeof TranslationService>;
    Users: Client<typeof UserService>;
}
